apiVersion: v1
kind: ServiceAccount
metadata:
  name: wpex-backend-sa
  namespace: wpex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wpex
  name: wpex-backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wpex-backend-rolebinding
  namespace: wpex
subjects:
- kind: ServiceAccount
  name: wpex-backend-sa
  namespace: wpex
roleRef:
  kind: Role
  name: wpex-backend-role
  apiGroup: rbac.authorization.k8s.io
